GET http://localhost:8080/api/v1/tasks
Accept: application/json

###

POST http://127.0.0.1:8080/api/v1/tasks
Content-Type: application/json
Accept: application/json

{
    "title": "task 1",
    "description": "description 1",
    "status": "pending"
}

###
GET http://127.0.0.1:8080/api/v1/tasks/1
Accept: application/json
